#!/bin/sh
# mkinitrd: 	create initrd image
# Author:	Dmitrij B. 

# Make initrd tree

. ./config || exit 1
. ./liblive || exit 1

INITRD_TREE=/tmp/initrd_tree_$$
MOUNT_DIR=/tmp/initrd_mount_$$
INITRD_IMG=$1

if [ ! -d "initrd" ]; then
	echo "The initrd not found";
        exit 1;
fi

debug "Creating initrd directories"
mkdir -p $INITRD_TREE/{etc,dev,bin,mnt,proc,lib,sbin,sys,tmp,var/log}

debug "Creating initrd devices"

mknod $INITRD_TREE/dev/console c 5 1
mknod $INITRD_TREE/dev/null c 1 3
mknod $INITRD_TREE/dev/ram b 1 1
mknod $INITRD_TREE/dev/systty c 4 0
mknod $INITRD_TREE/dev/tty c 5 0
mknod $INITRD_TREE/dev/tty1 c 4 1

loops=255
while [ $loops -ge 0 ]; do
   mknod $INITRD_TREE/dev/loop$loops b 7 $loops
   loops=$(($loops-1))
done

debug "Copying initrd files"
cp -Rpf initrd/* $INITRD_TREE/

debug "Copying initrd scripts"
cp -fp liblinux $INITRD_TREE/
cp -fp linuxrc  $INITRD_TREE/

debug "Calculating dependencies"
depmod -b $INITRD_TREE $KERNEL

debug "creating empty image file $INITRD_IMG"
dd if=/dev/zero of=$INITRD_IMG bs=1024 count=$INITRD_SIZE >/dev/null 2>/dev/null

debug "making filesystem"
mkfs -t ext2 -F -m 0 -b 1024 -i 1024 $INITRD_IMG 2>/dev/null >/dev/null

debug "creating empty directory $MOUNT_DIR"
rm -Rf $MOUNT_DIR
mkdir $MOUNT_DIR

debug "mounting $INITRD_IMG to it"
modprobe loop 2>/dev/null
mount -o loop $INITRD_IMG $MOUNT_DIR
if [ "$?" -ne 0 ]; then
   echo "Error mounting initrd! Not enough free loop devices?"
   exit 1
fi


debug "copying content of $INITRD_TREE to $MOUNT_DIR"
rmdir $MOUNT_DIR/lost+found
cp -Rp $INITRD_TREE/* $MOUNT_DIR

debug "unmounting $MOUNT_DIR"
umount $MOUNT_DIR

debug "gzipping $INITRD_IMG"
gzip --best $INITRD_IMG
