#!/bin/sh
#
# run this script to create a LiveCD in /tmp/livecd.iso

. ./config || exit 1
. ./liblive || exit 1


echo "Creating LiveCD from your Linux"

debug "Creating LiveCD directories"
mkdir -p $CD_ROOT/boot
mkdir -p $CD_ROOT/linux/base
mkdir -p $CD_ROOT/linux/optional

debug "Copying cd-root to $CD_ROOT"
cp -R cd-root/* $CD_ROOT/

debug "Creating initrd image"
./mkinitrd $CD_DATA/boot/initrd

debug "Creating compressed images..."
if [ -n $CREATE_IMAGES ]
then 
 for dir in $CREATE_IMAGES; do
   if [ -d $ROOT/$dir ]; then
     echo "base/$dir.mo"
     create_module $ROOT/$dir $CD_ROOT/linux/base/$dir.mo -keep-as-directory
     if [ $? -ne 0 ]; then exit; fi
   fi
  done
fi

debug "Creating iso..."
mkisofs -o "$ISO" -v -J -R -D -A "$CD_LABEL" -V "$CD_LABEL" \
-no-emul-boot -boot-info-table -boot-load-size 4 \
-b $CD_ROOT/boot/isolinux.bin -c $CD_ROOT/boot/isolinux.boot $CD_ROOT

echo "LiveCD created in $ISO"
